// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PrefixedValue {
    #[prost(double, tag = "1")]
    pub double_value: f64,
    #[prost(enumeration = "SiPrefix", tag = "2")]
    pub prefix: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParameterValue {
    #[prost(oneof = "parameter_value::Value", tags = "1, 2")]
    pub value: ::core::option::Option<parameter_value::Value>,
}
/// Nested message and enum types in `ParameterValue`.
pub mod parameter_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        PrefixedValue(super::PrefixedValue),
        #[prost(message, tag = "2")]
        ModelRef(super::ModelReference),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Parameter {
    #[prost(uint32, tag = "1")]
    pub uid: u32,
    #[prost(string, tag = "10")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "20")]
    pub default_value: ::core::option::Option<ParameterValue>,
    #[prost(string, tag = "30")]
    pub description: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "40")]
    pub properties: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelInterface {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub function_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "10")]
    pub parameters: ::prost::alloc::vec::Vec<Parameter>,
    #[prost(map = "string, string", tag = "20")]
    pub properties: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelReference {
    #[prost(string, tag = "1")]
    pub model_interface_name: ::prost::alloc::string::String,
    #[prost(map = "string, message", tag = "10")]
    pub arguments: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ParameterValue,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Terminal {
    #[prost(uint32, tag = "1")]
    pub uid: u32,
    #[prost(string, tag = "10")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "TerminalDirection", tag = "20")]
    pub direction: i32,
    #[prost(enumeration = "SignalDomain", tag = "30")]
    pub domain: i32,
    #[prost(uint32, tag = "40")]
    pub width: u32,
    #[prost(string, tag = "50")]
    pub cross_section: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "60")]
    pub properties: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TerminalReference {
    #[prost(string, tag = "1")]
    pub instance_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub terminal_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Connection {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "10")]
    pub source: ::core::option::Option<TerminalReference>,
    #[prost(message, optional, tag = "20")]
    pub target: ::core::option::Option<TerminalReference>,
    #[prost(enumeration = "SignalDomain", tag = "30")]
    pub domain: i32,
    #[prost(uint32, tag = "40")]
    pub weight: u32,
    #[prost(map = "string, string", tag = "50")]
    pub properties: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Bus {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "10")]
    pub width: u32,
    #[prost(enumeration = "SignalDomain", tag = "20")]
    pub domain: i32,
    #[prost(message, repeated, tag = "30")]
    pub connections: ::prost::alloc::vec::Vec<Connection>,
    #[prost(map = "string, string", tag = "40")]
    pub properties: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModuleReference {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub module_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub class_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "10")]
    pub parameter_values: ::prost::alloc::vec::Vec<ParameterValue>,
    #[prost(map = "string, message", tag = "20")]
    pub parameter_overrides: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ParameterValue,
    >,
    #[prost(map = "string, string", tag = "30")]
    pub properties: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Module {
    #[prost(uint32, tag = "1")]
    pub uid: u32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub class_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "10")]
    pub terminal: ::prost::alloc::vec::Vec<Terminal>,
    #[prost(message, repeated, tag = "20")]
    pub parameters: ::prost::alloc::vec::Vec<Parameter>,
    #[prost(message, repeated, tag = "30")]
    pub model_interfaces: ::prost::alloc::vec::Vec<ModelInterface>,
    #[prost(message, repeated, tag = "40")]
    pub module_references: ::prost::alloc::vec::Vec<ModuleReference>,
    #[prost(message, repeated, tag = "50")]
    pub connections: ::prost::alloc::vec::Vec<Connection>,
    #[prost(message, repeated, tag = "60")]
    pub buses: ::prost::alloc::vec::Vec<Bus>,
    #[prost(map = "string, string", tag = "70")]
    pub properties: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExternalModule {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub domain: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "10")]
    pub terminals: ::prost::alloc::vec::Vec<Terminal>,
    #[prost(message, repeated, tag = "20")]
    pub parameters: ::prost::alloc::vec::Vec<Parameter>,
    #[prost(map = "string, string", tag = "30")]
    pub properties: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Circuit {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub top_module: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "10")]
    pub modules: ::prost::alloc::vec::Vec<Module>,
    #[prost(message, repeated, tag = "20")]
    pub ext_modules: ::prost::alloc::vec::Vec<ExternalModule>,
    #[prost(map = "string, string", tag = "30")]
    pub properties: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CircuitReference {
    #[prost(string, tag = "1")]
    pub circuit_name: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "20")]
    pub properties: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Library {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "20")]
    pub circuit_reference: ::core::option::Option<CircuitReference>,
    #[prost(map = "string, string", tag = "30")]
    pub properties: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TerminalDirection {
    Inout = 0,
    Input = 1,
    Output = 2,
}
impl TerminalDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Inout => "Terminal_DIRECTION_INOUT",
            Self::Input => "Terminal_DIRECTION_INPUT",
            Self::Output => "Terminal_DIRECTION_OUTPUT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Terminal_DIRECTION_INOUT" => Some(Self::Inout),
            "Terminal_DIRECTION_INPUT" => Some(Self::Input),
            "Terminal_DIRECTION_OUTPUT" => Some(Self::Output),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SignalDomain {
    Unspecified = 0,
    Electrical = 1,
    Waveguide = 2,
}
impl SignalDomain {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SIGNAL_DOMAIN_UNSPECIFIED",
            Self::Electrical => "SIGNAL_DOMAIN_ELECTRICAL",
            Self::Waveguide => "SIGNAL_DOMAIN_WAVEGUIDE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SIGNAL_DOMAIN_UNSPECIFIED" => Some(Self::Unspecified),
            "SIGNAL_DOMAIN_ELECTRICAL" => Some(Self::Electrical),
            "SIGNAL_DOMAIN_WAVEGUIDE" => Some(Self::Waveguide),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SiPrefix {
    Unspecified = 0,
    Quecto = 1,
    Ronto = 2,
    Yocto = 3,
    Zepto = 4,
    Atto = 5,
    Femto = 6,
    Pico = 7,
    Nano = 8,
    Micro = 9,
    Milli = 10,
    Centi = 11,
    Deci = 12,
    Deca = 13,
    Hecto = 14,
    Kilo = 15,
    Mega = 16,
    Giga = 17,
    Tera = 18,
    Peta = 19,
    Exa = 20,
    Zetta = 21,
    Yotta = 22,
    Ronna = 23,
    Quetta = 24,
}
impl SiPrefix {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SI_PREFIX_UNSPECIFIED",
            Self::Quecto => "SI_PREFIX_QUECTO",
            Self::Ronto => "SI_PREFIX_RONTO",
            Self::Yocto => "SI_PREFIX_YOCTO",
            Self::Zepto => "SI_PREFIX_ZEPTO",
            Self::Atto => "SI_PREFIX_ATTO",
            Self::Femto => "SI_PREFIX_FEMTO",
            Self::Pico => "SI_PREFIX_PICO",
            Self::Nano => "SI_PREFIX_NANO",
            Self::Micro => "SI_PREFIX_MICRO",
            Self::Milli => "SI_PREFIX_MILLI",
            Self::Centi => "SI_PREFIX_CENTI",
            Self::Deci => "SI_PREFIX_DECI",
            Self::Deca => "SI_PREFIX_DECA",
            Self::Hecto => "SI_PREFIX_HECTO",
            Self::Kilo => "SI_PREFIX_KILO",
            Self::Mega => "SI_PREFIX_MEGA",
            Self::Giga => "SI_PREFIX_GIGA",
            Self::Tera => "SI_PREFIX_TERA",
            Self::Peta => "SI_PREFIX_PETA",
            Self::Exa => "SI_PREFIX_EXA",
            Self::Zetta => "SI_PREFIX_ZETTA",
            Self::Yotta => "SI_PREFIX_YOTTA",
            Self::Ronna => "SI_PREFIX_RONNA",
            Self::Quetta => "SI_PREFIX_QUETTA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SI_PREFIX_UNSPECIFIED" => Some(Self::Unspecified),
            "SI_PREFIX_QUECTO" => Some(Self::Quecto),
            "SI_PREFIX_RONTO" => Some(Self::Ronto),
            "SI_PREFIX_YOCTO" => Some(Self::Yocto),
            "SI_PREFIX_ZEPTO" => Some(Self::Zepto),
            "SI_PREFIX_ATTO" => Some(Self::Atto),
            "SI_PREFIX_FEMTO" => Some(Self::Femto),
            "SI_PREFIX_PICO" => Some(Self::Pico),
            "SI_PREFIX_NANO" => Some(Self::Nano),
            "SI_PREFIX_MICRO" => Some(Self::Micro),
            "SI_PREFIX_MILLI" => Some(Self::Milli),
            "SI_PREFIX_CENTI" => Some(Self::Centi),
            "SI_PREFIX_DECI" => Some(Self::Deci),
            "SI_PREFIX_DECA" => Some(Self::Deca),
            "SI_PREFIX_HECTO" => Some(Self::Hecto),
            "SI_PREFIX_KILO" => Some(Self::Kilo),
            "SI_PREFIX_MEGA" => Some(Self::Mega),
            "SI_PREFIX_GIGA" => Some(Self::Giga),
            "SI_PREFIX_TERA" => Some(Self::Tera),
            "SI_PREFIX_PETA" => Some(Self::Peta),
            "SI_PREFIX_EXA" => Some(Self::Exa),
            "SI_PREFIX_ZETTA" => Some(Self::Zetta),
            "SI_PREFIX_YOTTA" => Some(Self::Yotta),
            "SI_PREFIX_RONNA" => Some(Self::Ronna),
            "SI_PREFIX_QUETTA" => Some(Self::Quetta),
            _ => None,
        }
    }
}
